---
title: "Worship Matters"
subtitle: "Session 12: Loving Your Musicians and Pastor"
date: today
author: Hans Martinez
format:
  revealjs: 
    theme: default
    link-external-newwindow: true
    incremental: true
---

## Introducción

- Reunión pasada iniciamos: Relaciones Correctas
  - Tu iglesia  
- Última reunion:
  - Tu equipo
  - Tu pastor

## Video

[Link](https://vimeo.com/224339062)

## Preguntas de reflexión


1. ¿Tienes claro tu papel en el ministerio de adoración? (Si no, habla con tu pastor y obtén aclaración.) ¿Son tus expectativas apropiadas para tu papel, temporada de vida, tamaño de la iglesia, tamaño del equipo, etc.?
2. Bob dice: "El ánimo debe ser consistente, privado y público." ¿En cuál de esos necesitas crecer más? Discute pasos prácticos que puedes tomar para crecer en esa área.
3. ¿Cómo respondes a la evaluación? Discute tu nivel de apertura/deseo de ser evaluado.

## Preguntas de reflexión

4. ¿Por qué es tan importante la evaluación para un equipo? ¿Qué puedes hacer para contribuir a una cultura de evaluación saludable (es decir, una que sea útil y no meramente crítica)?
5. ¿Cuáles son algunas verdades bíblicas que pueden ayudar a un equipo a disfrutar más lo que hacen, en lugar de siempre sentirse estresados o bajo presión?
6. ¿Cuáles son algunos pasos que puedes tomar para entender mejor a tu pastor, comunicarte con tu pastor y servir a tu pastor?
7. ¿Cuál es una verdad o aplicación que te ha ayudado más del Video Intensivo de Worship Matters?