---
title: "Worship Matters"
subtitle: "Session 11: Loving Your Family and Church"
date: today
author: Hans Martinez
format:
  revealjs: 
    theme: default
    link-external-newwindow: true
    incremental: true
---

## Introducción

- Reunión pasada terminamos: TENSIONES SALUDABLES
- Tensiones saludables: balance entre puntos de vista contrastantes sobre la liturgia
- Última sección: Relaciones Correctas


## Relaciones Correctas

- Tu iglesia
- Tu equipo
- Tu pastor

## Video

[Link](https://vimeo.com/223809308)

## Preguntas de reflexión


1. ¿Cuáles son algunas formas en las que puedes asegurarte de que tu familia no está siendo sacrificada en el altar del ministerio?

1. ¿Cuáles son algunas formas en las que puedes expresar tu amor a las personas en tu iglesia?

1. ¿Cómo sueles responder a la crítica o corrección?

## Preguntas de reflexión

4. ¿Cómo cambia el evangelio la manera en que naturalmente recibiríamos la crítica/corrección?

5. ¿Cuáles son algunas formas de recibir elogios?

6. ¿Qué significa amar a las personas a las que sirves liderándolas teológicamente? ¿Cómo sientes que lo estás haciendo en ese aspecto? (Busca la opinión de los miembros de tu equipo y de tu pastor sobre esta pregunta.)