---
title: "Worship Matters"
subtitle: "Session 9: Healthy Tensions, Part 1"
date: today
author: Hans Martinez
format:
  revealjs: 
    theme: default
    link-external-newwindow: true
    incremental: true
---

## Introducción

- Reunión pasada terminamos de estudiar la definición the *líder de alabanza*
- En esta sesión iniciamos: TENSIONES SALUDABLES
- Tensiones saludables: balance entre puntos de vista contrastantes sobre la liturgia


## Tres principios sobre el orden del servicio:

1. Hacer lo que Dios claramente ordena
2. No hacer lo que Dios claramente prohíbe
3. Usar la sabiduría de Dios en todo lo demás

## Video

[Link](https://vimeo.com/222888465)

## Preguntas de reflexión

1. ¿Cómo se comunica la trascendencia de Dios en las reuniones de adoración? ¿Cómo se comunica la inmanencia de Dios en las reuniones de adoración? ¿Por qué es importante mantener esta tensión?
2. ¿Tiendes a poner más peso en la "mente" o en el "corazón" cuando se trata de adorar a Dios a través de la música? ¿Cuáles son algunas formas de crecer en un equilibrio más saludable de los dos?

## Preguntas de reflexión

3. Pocas personas discrepan sobre la importancia del componente interno (compromiso del corazón) en la adoración. Discute tu punto de vista sobre el papel de la expresividad física.

4. ¿Qué beneficios experimentamos al adorar a Dios y darle gloria juntos?

## Preguntas de reflexión

5. Pregunta a las otras personas de tu equipo si tienden a mantener los ojos abiertos o no.
6. Además de cantar canciones centradas en Dios y edificantes, ¿qué otras cosas podemos hacer/decir para fortalecer la dimensión horizontal de nuestra adoración?